// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDloo4wlnvnv2ILKDrPcYZEc2OIRuLSDK4',
    appId: '1:1055066887450:web:1782a0e47ea4701b3288a3',
    messagingSenderId: '1055066887450',
    projectId: 'reddit-b52f9',
    authDomain: 'reddit-b52f9.firebaseapp.com',
    storageBucket: 'reddit-b52f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_bLfDb6A_86YXJrKrxRV9hvuLAYWtgWk',
    appId: '1:1055066887450:android:d6f9187e741f0ad63288a3',
    messagingSenderId: '1055066887450',
    projectId: 'reddit-b52f9',
    storageBucket: 'reddit-b52f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi4c22y452NzZOKss9nsI-bY5lmVY2vJI',
    appId: '1:1055066887450:ios:de4708b8b18c62693288a3',
    messagingSenderId: '1055066887450',
    projectId: 'reddit-b52f9',
    storageBucket: 'reddit-b52f9.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDloo4wlnvnv2ILKDrPcYZEc2OIRuLSDK4',
    appId: '1:1055066887450:web:8404c477724760313288a3',
    messagingSenderId: '1055066887450',
    projectId: 'reddit-b52f9',
    authDomain: 'reddit-b52f9.firebaseapp.com',
    storageBucket: 'reddit-b52f9.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi4c22y452NzZOKss9nsI-bY5lmVY2vJI',
    appId: '1:1055066887450:ios:de4708b8b18c62693288a3',
    messagingSenderId: '1055066887450',
    projectId: 'reddit-b52f9',
    storageBucket: 'reddit-b52f9.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );

}